"""applications and application_events

Revision ID: 33e3e4c22650
Revises: 08bc67eec84e
Create Date: 2026-08-17

Phase 1 core schema. Generated with --autogenerate and then read line by line
before being applied, which is the only safe way to use autogenerate: it is a
good assistant and a bad authority.

Reviewed and confirmed:
  * both CHECK constraints list exactly the enum values from app/enums.py
  * the FK carries ON DELETE CASCADE, so events cannot outlive their application
  * ix_application_events_scheduled_for is a PARTIAL index (WHERE scheduled_for
    IS NOT NULL) — it stays small because most events have no future date
  * every timestamp is TIMESTAMPTZ, never naive
  * downgrade() drops things in reverse dependency order
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33e3e4c22650'
down_revision: Union[str, Sequence[str], None] = '08bc67eec84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_key', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=False),
    sa.Column('role_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('application_channel', sa.String(length=32), nullable=False),
    sa.Column('job_url', sa.Text(), nullable=True),
    sa.Column('job_url_canonical', sa.Text(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_mode', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("application_channel IN ('linkedin', 'company_site', 'recruiter', 'referral', 'job_board', 'other')", name='ck_applications_application_channel'),
    sa.CheckConstraint("status IN ('saved', 'applied', 'recruiter_contact', 'hr_interview', 'technical_interview', 'take_home', 'final_interview', 'offer', 'accepted', 'rejected', 'withdrawn', 'on_hold')", name='ck_applications_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_company_role', 'applications', ['company_key', 'role_key'], unique=False)
    op.create_index('ix_applications_job_url_canonical', 'applications', ['job_url_canonical'], unique=False)
    op.create_index('ix_applications_status_applied_at', 'applications', ['status', 'applied_at'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('created', 'status_changed', 'note_added', 'document_attached', 'interview_scheduled', 'interview_completed', 'assignment_received', 'assignment_submitted', 'offer_received', 'followed_up', 'imported')", name='ck_application_events_event_type'),
    sa.CheckConstraint("source IN ('manual', 'extension', 'gmail', 'system')", name='ck_application_events_source'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_events_application_occurred', 'application_events', ['application_id', 'occurred_at'], unique=False)
    op.create_index('ix_application_events_scheduled_for', 'application_events', ['scheduled_for'], unique=False, postgresql_where=sa.text('scheduled_for IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_events_scheduled_for', table_name='application_events', postgresql_where=sa.text('scheduled_for IS NOT NULL'))
    op.drop_index('ix_application_events_application_occurred', table_name='application_events')
    op.drop_table('application_events')
    op.drop_index('ix_applications_status_applied_at', table_name='applications')
    op.drop_index('ix_applications_job_url_canonical', table_name='applications')
    op.drop_index('ix_applications_company_role', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
